version: '3'

services:
  app:
    build: .
    tty: true
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes: 
      - ./:/usr/src/app
      - /usr/src/app/node_modules
